version: '3'
services:
  api:
    build: ./api
    image: localhost:5000/rootme_api_python

  varnish:
    build: ./varnish
    image: localhost:5000/rootme_api_varnish
    ports:
      - "8001:8080"
