version: '3'
services:
  redis:
    image: redis
    restart: always
    networks:
      - backend
  api:
    restart: always
    build: 
      context: ./api
    ports: 
      - "3000:3000"
    networks:
      - frontend
      - backend
  worker:
    restart: always
    build:
      context: ./worker
    networks:
      - backend
  discord:
    restart: always
    build:
      context: ./bot_discord
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
