version: '3'
services:
  web_server:
    build: ./web_server
    expose:
     - "5000"
    environment:
     - NGINX_PORT=80


  api:
    build: ./api
    environment:
      GUNICORN_PORT: 5000
    expose:
     - "5000"

  varnish:
    build: ./varnish
    environment:
      VARNISH_PORT: 5001
    ports:
      - "8080:5001"
